### ISSUE TITLE
logcat spam

### ISSUE THREAD

**Issue by steelbytes** [kinecosystem/kin-sdk-android#54]
crazy amounts of this spamming my logs

java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:577)
        at java.lang.Integer.parseInt(Integer.java:650)
        at kin.base.responses.Response.setHeaders(Response.java:10)
        at kin.base.requests.ResponseHandler.handleResponse(ResponseHandler.java:70)
        at kin.base.requests.ResponseHandler.handleGetRequest(ResponseHandler.java:31)
        at kin.base.requests.AccountsRequestBuilder.account(AccountsRequestBuilder.java:29)
        at kin.base.requests.AccountsRequestBuilder.account(AccountsRequestBuilder.java:40)
        at kin.sdk.TransactionSender.loadAccount(TransactionSender.java:175)
        at kin.sdk.TransactionSender.verifyAddresseeAccount(TransactionSender.java:169)
        at kin.sdk.TransactionSender.buildTransaction(TransactionSender.java:58)
        at kin.sdk.TransactionSender.buildTransaction(TransactionSender.java:46)
        at kin.sdk.KinAccountImpl.buildTransactionSync(KinAccountImpl.java:42)
        at kin.sdk.AbstractKinAccount$1.call(AbstractKinAccount.java:18)
        at kin.sdk.AbstractKinAccount$1.call(AbstractKinAccount.java:15)
        at kin.utils.Request$1.run(Request.java:65)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by chaseeb** [comment]
I'll make sure the devs take a look when they're back in the office on Sunday

**Comment by cohenalex** [comment]
Hi @steelbytes Thanks for reaching out. We are looking into this and will update you once we have an update.

**Comment by cohenalex** [comment]
Fixed in version 1.0.7:
https://github.com/kinecosystem/kin-sdk-android/releases/tag/1.0.7
